AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
   PostFunction:
     Type: AWS::Serverless::Function
     Properties:
        Role: arn:aws:iam::764954741168:role/logger
        Handler: logEvents.handler
        Runtime: nodejs6.10
        Environment:
          Variables:
             LOG_STREAM_NAME: aws-logger-delivery-stream
        CodeUri: s3://aws-logger-deployments/logger-lambda.zip
        Events:
          GetResource:
            Type: Api
            Properties:
               Path: /logs
               Method: post
